import React, { useEffect, useState } from "react";
import { OrderResponse, PaymentResponse } from "../../../services/Commerce";
import OrderService from "../../../services/OrderService";
import PaymentService from "../../../services/PaymentService";

export const CommerceAdmin: React.FC = () => {
  const [orders, setOrders] = useState<OrderResponse[]>([]);
  const [payments, setPayments] = useState<PaymentResponse[]>([]);
  const [error, setError] = useState("");
  const [busy, setBusy] = useState("");
  const load = () => Promise.all([OrderService.getAllOrders(), PaymentService.getPending()]).then(([ordersResult, paymentsResult]) => { setOrders(ordersResult.data.data ?? []); setPayments(paymentsResult.data.data ?? []); }).catch((e) => setError(e.response?.data?.message ?? "Could not load commerce data."));
  useEffect(() => { load(); }, []);
  const verify = async (paymentId: string) => { try { setBusy(paymentId); await PaymentService.verify(paymentId); load(); } catch (e: any) { setError(e.response?.data?.message ?? "Payment could not be verified."); } finally { setBusy(""); } };
  const reject = async (paymentId: string) => { const rejectionReason = window.prompt("Reason for rejecting this payment?"); if (!rejectionReason?.trim()) return; try { setBusy(paymentId); await PaymentService.reject(paymentId, rejectionReason); load(); } catch (e: any) { setError(e.response?.data?.message ?? "Payment could not be rejected."); } finally { setBusy(""); } };
  const updateStatus = async (orderId: string, status: string) => { try { setBusy(orderId); await OrderService.updateStatus(orderId, status); load(); } catch (e: any) { setError(e.response?.data?.message ?? "Status could not be updated."); } finally { setBusy(""); } };
  return <div><p className="text-amber-700 font-bold text-xs uppercase tracking-widest">Commerce operations</p><h1 className="text-3xl font-black text-stone-900">Orders & payments</h1>{error && <div className="mt-5 p-3 rounded-xl bg-red-50 text-red-700">{error}</div>}<section className="mt-8"><h2 className="text-xl font-black">Payments awaiting verification</h2>{!payments.length ? <p className="mt-3 text-stone-500">No payment proofs awaiting review.</p> : <div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><thead className="text-left text-stone-500 border-b"><tr><th className="py-3">Payment</th><th>Order</th><th>Amount</th><th>Proof</th><th /></tr></thead><tbody>{payments.map((payment) => <tr className="border-b border-stone-100" key={payment.paymentId}><td className="py-4 font-bold">{payment.transactionId || payment.paymentId}</td><td>{payment.orderId}</td><td>₹{payment.amount.toLocaleString("en-IN")}</td><td>{payment.screenshotUrl ? <a className="text-amber-700 font-bold" target="_blank" rel="noreferrer" href={payment.screenshotUrl}>View screenshot</a> : "—"}</td><td className="space-x-2"><button disabled={busy === payment.paymentId} onClick={() => verify(payment.paymentId)} className="rounded-lg px-3 py-2 bg-amber-700 text-white font-bold">Verify</button><button disabled={busy === payment.paymentId} onClick={() => reject(payment.paymentId)} className="rounded-lg px-3 py-2 border border-red-200 text-red-700 font-bold">Reject</button></td></tr>)}</tbody></table></div>}</section><section className="mt-12"><h2 className="text-xl font-black">All orders</h2><div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><thead className="text-left text-stone-500 border-b"><tr><th className="py-3">Order</th><th>Customer</th><th>Amount</th><th>Status</th><th /></tr></thead><tbody>{orders.map((order) => <tr key={order.orderId} className="border-b border-stone-100"><td className="py-4 font-bold">{order.orderNumber}</td><td>{order.userId}</td><td>₹{order.finalAmount.toLocaleString("en-IN")}</td><td><span className="font-bold text-amber-700">{order.orderStatus.replaceAll("_", " ")}</span></td><td><select disabled={busy === order.orderId} value={order.orderStatus} onChange={(event) => updateStatus(order.orderId, event.target.value)} className="rounded-lg border border-stone-300 px-2 py-1"><option value="CONFIRMED">Confirmed</option><option value="PROCESSING">Processing</option><option value="SHIPPED">Shipped</option><option value="DELIVERED">Delivered</option><option value="CANCELLED">Cancelled</option></select></td></tr>)}</tbody></table></div></section></div>;
};
