import React from "react";

const Label: React.FC<{ children: React.ReactNode }> = ({ children }) => <p className="text-xs font-bold uppercase tracking-widest text-stone-400">{children}</p>;

export const TestimonialsAdmin: React.FC = () => {
  const samples = [
    ["Client testimonial", "A thoughtful, professional consultation that made our home feel balanced and welcoming.", "Bhopal"],
    ["Project feedback", "Clear guidance, timely support, and a solution suited to our family’s requirements.", "Indore"],
    ["Consultation review", "The process was simple from the first call to the final recommendations.", "Delhi"],
  ];
  return <section><p className="text-amber-700 font-bold text-xs uppercase tracking-widest">Static preview</p><h1 className="mt-2 text-3xl font-black text-stone-900">Testimonials</h1><p className="mt-3 max-w-2xl text-stone-500">This section is ready for testimonial management. It is currently static and will be connected to the backend later.</p><div className="mt-8 grid md:grid-cols-3 gap-5">{samples.map(([title, quote, city]) => <article key={city} className="rounded-3xl border border-stone-100 bg-white p-6 shadow-sm"><i className="fa-solid fa-quote-left text-amber-600 text-xl"></i><p className="mt-4 text-sm leading-6 text-stone-600">{quote}</p><div className="mt-6 border-t border-stone-100 pt-4"><p className="font-bold text-stone-900">{title}</p><p className="text-xs text-stone-400">{city}</p></div></article>)}</div><div className="mt-8 rounded-2xl bg-amber-50 border border-amber-100 p-5 text-sm text-amber-900"><strong>Planned connection:</strong> add, edit, delete, image upload and display order will be enabled with the testimonial API.</div></section>;
};

export const ConfigAdmin: React.FC = () => <section><p className="text-amber-700 font-bold text-xs uppercase tracking-widest">Static preview</p><h1 className="mt-2 text-3xl font-black text-stone-900">Brand configuration</h1><p className="mt-3 text-stone-500">A preview of the settings that will control the public website.</p><div className="mt-8 grid md:grid-cols-2 gap-6">{[["Accent colour", "Warm amber #B45309"], ["Complaint WhatsApp", "Configured in site settings"], ["Hero media", "Image or video background"], ["About content", "Title, short intro and full narrative"]].map(([label, value]) => <div key={label} className="rounded-2xl border border-stone-100 bg-white p-6"><Label>{label}</Label><p className="mt-3 font-bold text-stone-800">{value}</p><span className="mt-4 inline-block rounded-lg bg-stone-100 px-2 py-1 text-xs font-bold text-stone-500">Static for now</span></div>)}</div></section>;

export const SecurityInfoAdmin: React.FC = () => <section><p className="text-red-600 font-bold text-xs uppercase tracking-widest">Administration guide</p><h1 className="mt-2 text-3xl font-black text-stone-900">Security information</h1><div className="mt-8 max-w-3xl space-y-6"><article className="rounded-3xl border border-stone-200 bg-stone-50 p-7"><h2 className="text-xl font-black">How to change admin credentials</h2><p className="mt-3 text-sm leading-6 text-stone-600">Keep admin credentials in environment variables rather than in frontend source code.</p><ol className="mt-5 space-y-3 text-sm text-stone-700 list-decimal list-inside"><li>Open your deployment platform settings.</li><li>Find the Environment Variables section.</li><li>Set or update <strong>ADMIN_ID</strong> and <strong>ADMIN_PASS</strong>.</li></ol></article><article className="rounded-3xl border border-amber-100 bg-amber-50 p-7"><h2 className="text-xl font-black text-amber-950">Payment safety</h2><p className="mt-3 text-sm leading-6 text-amber-900">The application stores payment proof and transaction IDs for verification. It should never store card or banking credentials.</p></article></div></section>;

export const CloudSetupAdmin: React.FC = () => <section><p className="text-amber-700 font-bold text-xs uppercase tracking-widest">Deployment guide</p><h1 className="mt-2 text-3xl font-black text-stone-900">Cloud setup</h1><p className="mt-3 text-stone-500">Use these steps when connecting a hosted frontend and backend.</p><div className="mt-8 max-w-3xl space-y-5">{[["1", "Set frontend API URL", "Configure the deployed backend base URL instead of localhost."], ["2", "Add deployment environment values", "Add the needed service keys in the provider’s protected environment settings."], ["3", "Deploy and validate", "Confirm login, checkout, payment-proof upload and admin access after deployment."]].map(([number, title, copy]) => <article key={number} className="flex gap-5 rounded-2xl border border-stone-100 bg-white p-6"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-amber-100 font-black text-amber-700">{number}</div><div><h2 className="font-black text-stone-900">{title}</h2><p className="mt-1 text-sm leading-6 text-stone-500">{copy}</p></div></article>)}</div></section>;
